//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Mappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.comment_answer = new HashSet<comment_answer>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string text { get; set; }
        public Nullable<int> movie_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> person_id { get; set; }
    
        public virtual ICollection<comment_answer> comment_answer { get; set; }
        public virtual movie movie { get; set; }
        public virtual person person { get; set; }
        public virtual user user { get; set; }
    }
}
