//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesEntities : DbContext
    {
        public MoviesEntities()
            : base("name=MoviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cast> cast { get; set; }
        public DbSet<comment> comment { get; set; }
        public DbSet<comment_answer> comment_answer { get; set; }
        public DbSet<image> image { get; set; }
        public DbSet<image_relation> image_relation { get; set; }
        public DbSet<movie> movie { get; set; }
        public DbSet<movie_relation> movie_relation { get; set; }
        public DbSet<person> person { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<users_vote> users_vote { get; set; }
    }
}
