//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_vote
    {
        public int user_id { get; set; }
        public int relation_id { get; set; }
        public bool vote { get; set; }
    
        public virtual movie_relation movie_relation { get; set; }
        public virtual user user { get; set; }
    }
}
